#ifndef _SLATE_OPTIONS_H
#define _SLATE_OPTIONS_H

#include <unistd.h>

#ifdef _POSIX_ADVISORY_INFO
#define POSIX_ADVISORY_INFO _POSIX_ADVISORY_INFO
#endif
#ifdef _POSIX_CHOWN_RESTRICTED
#define POSIX_CHOWN_RESTRICTED _POSIX_CHOWN_RESTRICTED
#endif
#ifdef _POSIX_IPV6
#define POSIX_IPV6 _POSIX_IPV6
#endif
#ifdef _POSIX_JOB_CONTROL
#define POSIX_JOB_CONTROL _POSIX_JOB_CONTROL
#endif
#ifdef _POSIX_MAPPED_FILES
#define POSIX_MAPPED_FILES _POSIX_MAPPED_FILES
#endif
#ifdef _POSIX_MEMLOCK
#define POSIX_MEMLOCK _POSIX_MEMLOCK
#endif
#ifdef _POSIX_MEMLOCK_RANGE
#define POSIX_MEMLOCK_RANGE _POSIX_MEMLOCK_RANGE
#endif
#ifdef _POSIX_MEMORY_PROTECTION
#define POSIX_MEMORY_PROTECTION _POSIX_MEMORY_PROTECTION
#endif
#ifdef _POSIX_MESSAGE_PASSING
#define POSIX_MESSAGE_PASSING _POSIX_MESSAGE_PASSING
#endif
#ifdef _POSIX_FSYNC
#define POSIX_FSYNC _POSIX_FSYNC
#endif
#ifdef _POSIX_NO_TRUNC
#define POSIX_NO_TRUNC _POSIX_NO_TRUNC
#endif
#ifdef _POSIX_RAW_SOCKETS
#define POSIX_RAW_SOCKETS _POSIX_RAW_SOCKETS
#endif
#ifdef _POSIX_REALTIME_SIGNALS
#define POSIX_REALTIME_SIGNALS _POSIX_REALTIME_SIGNALS
#endif
#ifdef _POSIX_REGEXP
#define POSIX_REGEXP _POSIX_REGEXP
#endif
#ifdef _POSIX_SAVED_IDS
#define POSIX_SAVED_IDS _POSIX_SAVED_IDS
#endif
#ifdef _POSIX_SHELL
#define POSIX_SHELL _POSIX_SHELL
#endif
#ifdef _POSIX_SPAWN
#define POSIX_SPAWN _POSIX_SPAWN
#endif
#ifdef _POSIX_VDISABLE
#define POSIX_VDISABLE _POSIX_VDISABLE
#endif
#ifdef _POSIX_THREADS
#define POSIX_THREADS _POSIX_THREADS
#endif
#ifdef _POSIX_THREAD_PROCESS_SHARED
#define POSIX_THREAD_PROCESS_SHARED _POSIX_THREAD_PROCESS_SHARED
#endif
#ifdef _POSIX_THREAD_SAFE_FUNCTIONS
#define POSIX_THREAD_SAFE_FUNCTIONS _POSIX_THREAD_SAFE_FUNCTIONS
#endif
#ifdef _POSIX_THREAD_ATTR_STACKADDR
#define POSIX_THREAD_ATTR_STACKADDR _POSIX_THREAD_ATTR_STACKADDR
#endif
#ifdef _POSIX_THREAD_ATTR_STACKSIZE
#define POSIX_THREAD_ATTR_STACKSIZE _POSIX_THREAD_ATTR_STACKSIZE
#endif
#ifdef _POSIX_THREAD_PRIORITY_SCHEDULING
#define POSIX_THREAD_PRIORITY_SCHEDULING _POSIX_THREAD_PRIORITY_SCHEDULING
#endif
#ifdef _POSIX_THREAD_CPUTIME
#define POSIX_THREAD_CPUTIME _POSIX_THREAD_CPUTIME
#endif
#ifdef _POSIX_TIMERS
#define POSIX_TIMERS _POSIX_TIMERS
#endif
#ifdef _POSIX_TIMEOUTS
#define POSIX_TIMEOUTS _POSIX_TIMEOUTS
#endif
#ifdef _POSIX_MONOTONIC_CLOCK
#define POSIX_MONOTONIC_CLOCK _POSIX_MONOTONIC_CLOCK
#endif
#ifdef _POSIX_CPUTIME
#define POSIX_CPUTIME _POSIX_CPUTIME
#endif
#ifdef _POSIX_CLOCK_SELECTION
#define POSIX_CLOCK_SELECTION _POSIX_CLOCK_SELECTION
#endif
#ifdef _POSIX_BARRIERS
#define POSIX_BARRIERS _POSIX_BARRIERS
#endif
#ifdef _POSIX_SPIN_LOCKS
#define POSIX_SPIN_LOCKS _POSIX_SPIN_LOCKS
#endif
#ifdef _POSIX_READER_WRITER_LOCKS
#define POSIX_READER_WRITER_LOCKS _POSIX_READER_WRITER_LOCKS
#endif
#ifdef _POSIX_ASYNCHRONOUS_IO
#define POSIX_ASYNCHRONOUS_IO _POSIX_ASYNCHRONOUS_IO
#endif
#ifdef _POSIX_SEMAPHORES
#define POSIX_SEMAPHORES _POSIX_SEMAPHORES
#endif
#ifdef _POSIX_SHARED_MEMORY_OBJECTS
#define POSIX_SHARED_MEMORY_OBJECTS _POSIX_SHARED_MEMORY_OBJECTS
#endif

#endif
