enum {
  PTRACE_GET_THREAD_AREA = 25,
  PTRACE_SET_THREAD_AREA = 26,
  PTRACE_ARCH_PRCTL = 30,
  PTRACE_SYSEMU = 31,
  PTRACE_SYSEMU_SINGLESTEP = 32,
  PTRACE_SINGLEBLOCK = 33,

  PT_GET_THREAD_AREA = PTRACE_GET_THREAD_AREA,
  PT_SET_THREAD_AREA = PTRACE_SET_THREAD_AREA,
  PT_ARCH_PRCTL = PTRACE_ARCH_PRCTL,
  PT_SYSEMU = PTRACE_SYSEMU,
  PT_SYSEMU_SINGLESTEP = PTRACE_SYSEMU_SINGLESTEP,
  PT_STEPBLOCK = PTRACE_SINGLEBLOCK,
};
