[package]
name = "slate-c2rust"
version = "0.1.0"
edition = "2024"
default-run = "slate"
description = "A C to Rust transpiler with a built-in C frontend"
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["c", "rust", "transpiler", "compiler"]
categories = ["compilers", "command-line-utilities"]
include = ["/src", "/build.rs", "/LICENSE-*", "/vendor/aligned", "/vendor/bitint", "/vendor/num-complex"]

[lib]
name = "slate"

[[bin]]
name = "slate"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
libc.workspace = true
serde_json.workspace = true
shlex.workspace = true
thiserror.workspace = true
ordered-float.workspace = true
miette.workspace = true
rayon.workspace = true
slate-parser.workspace = true
slate-sysroots = { workspace = true, optional = true }
prettyplease.workspace = true
syn = { workspace = true, features = ["full", "parsing"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mimalloc.workspace = true

[features]
default = ["sysroot-install", "syntax-highlight"]
sysroot-install = ["dep:slate-sysroots"]
syntax-highlight = ["miette/syntect-highlighter"]

[lints.clippy]
large_enum_variant = "allow"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
