#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Pass {
    Goto,
    Switch,
    EarlyInlineTemps,
    AnonymousStructs,
    ParamSpills,
    ZeroInit,
    StructFieldInit,
    SingletonScopes,
    CompoundAssign,
    Swap,
    ForContinue,
    ConstantIndexCasts,
    UnnecessaryCasts,
    CallArgs,
    Retval,
    FinalReturnTemps,
    LazySingleton,
    DropCallResults,
    StringLift,
    StringParams,
    PtrLen,
    SliceIndex,
    SliceLoop,
    SliceSwap,
    SliceReduce,
    RangeLoop,
    VaList,
    RemoveMut,
    StringCopy,
    StringLibc,
    CTypeLibc,
    SortSearch,
    HeapOwnership,
    OptionBoxLocals,
    InterproceduralAllocPromotion,
    DeadLocals,
    SprintfFormat,
    PrintfFormat,
    PrintfStream,
    CStrings,
    Stdio,
    Perror,
    MemchrPreludeFixupCalls,
    NullablePointer,
    StringLiftFixupCStrings,
    MemchrPrelude,
    PtrCopy,
    MemMove,
    MemSet,
    MemCmp,
    ArrayElementPointerOrigin,
    ArrayElementPointerParamHoist,
    BufferCursor,
    AtomicLocals,
    LateInlineTemps,
    AtomicCompareExchange,
    AssertRecovery,
    VarAliases,
    ConstantConditions,
    LibcExit,
    UnusedItems,
    UnusedParams,
    FinalReturns,
    MainZeroExit,
    PruneUnusedDefinitions,
    SetjmpRecovery,
}

impl Pass {
    pub const ALL: &'static [Pass] = &[
        Pass::Goto,
        Pass::Switch,
        Pass::EarlyInlineTemps,
        Pass::AnonymousStructs,
        Pass::ParamSpills,
        Pass::ZeroInit,
        Pass::StructFieldInit,
        Pass::SingletonScopes,
        Pass::CompoundAssign,
        Pass::Swap,
        Pass::ForContinue,
        Pass::ConstantIndexCasts,
        Pass::UnnecessaryCasts,
        Pass::CallArgs,
        Pass::Retval,
        Pass::FinalReturnTemps,
        Pass::LazySingleton,
        Pass::DropCallResults,
        Pass::StringLift,
        Pass::StringParams,
        Pass::PtrLen,
        Pass::SliceIndex,
        Pass::SliceLoop,
        Pass::SliceSwap,
        Pass::SliceReduce,
        Pass::RangeLoop,
        Pass::VaList,
        Pass::RemoveMut,
        Pass::StringCopy,
        Pass::StringLibc,
        Pass::CTypeLibc,
        Pass::SortSearch,
        Pass::HeapOwnership,
        Pass::OptionBoxLocals,
        Pass::InterproceduralAllocPromotion,
        Pass::DeadLocals,
        Pass::SprintfFormat,
        Pass::PrintfFormat,
        Pass::PrintfStream,
        Pass::CStrings,
        Pass::Stdio,
        Pass::Perror,
        Pass::MemchrPreludeFixupCalls,
        Pass::NullablePointer,
        Pass::StringLiftFixupCStrings,
        Pass::MemchrPrelude,
        Pass::PtrCopy,
        Pass::MemMove,
        Pass::MemSet,
        Pass::MemCmp,
        Pass::ArrayElementPointerOrigin,
        Pass::ArrayElementPointerParamHoist,
        Pass::BufferCursor,
        Pass::AtomicLocals,
        Pass::LateInlineTemps,
        Pass::AtomicCompareExchange,
        Pass::AssertRecovery,
        Pass::VarAliases,
        Pass::ConstantConditions,
        Pass::LibcExit,
        Pass::UnusedItems,
        Pass::UnusedParams,
        Pass::FinalReturns,
        Pass::MainZeroExit,
        Pass::PruneUnusedDefinitions,
        Pass::SetjmpRecovery,
    ];

    pub fn name(self) -> &'static str {
        match self {
            Pass::Goto => "goto",
            Pass::Switch => "switch",
            Pass::EarlyInlineTemps => "early_inline_temps",
            Pass::AnonymousStructs => "anonymous_structs",
            Pass::ParamSpills => "param_spills",
            Pass::ZeroInit => "zero_init",
            Pass::StructFieldInit => "struct_field_init",
            Pass::SingletonScopes => "singleton_scopes",
            Pass::CompoundAssign => "compound_assign",
            Pass::Swap => "swap",
            Pass::ForContinue => "for_continue",
            Pass::ConstantIndexCasts => "constant_index_casts",
            Pass::UnnecessaryCasts => "unnecessary_casts",
            Pass::CallArgs => "call_args",
            Pass::Retval => "retval",
            Pass::FinalReturnTemps => "final_return_temps",
            Pass::LazySingleton => "lazy_singleton",
            Pass::DropCallResults => "drop_call_results",
            Pass::StringLift => "string_lift",
            Pass::StringParams => "string_params",
            Pass::PtrLen => "ptr_len",
            Pass::SliceIndex => "slice_index",
            Pass::SliceLoop => "slice_loop",
            Pass::SliceSwap => "slice_swap",
            Pass::SliceReduce => "slice_reduce",
            Pass::RangeLoop => "range_loop",
            Pass::VaList => "va_list",
            Pass::RemoveMut => "remove_mut",
            Pass::StringCopy => "string_copy",
            Pass::StringLibc => "string_libc",
            Pass::CTypeLibc => "ctype_libc",
            Pass::SortSearch => "sort_search",
            Pass::HeapOwnership => "heap_ownership",
            Pass::OptionBoxLocals => "option_box_locals",
            Pass::InterproceduralAllocPromotion => "interprocedural_alloc_promotion",
            Pass::DeadLocals => "dead_locals",
            Pass::SprintfFormat => "sprintf_format",
            Pass::PrintfFormat => "printf_format",
            Pass::PrintfStream => "printf_stream",
            Pass::CStrings => "c_strings",
            Pass::Stdio => "stdio",
            Pass::Perror => "perror",
            Pass::MemchrPreludeFixupCalls => "memchr_prelude::fixup_calls",
            Pass::NullablePointer => "nullable_pointer",
            Pass::StringLiftFixupCStrings => "string_lift::fixup_c_strings",
            Pass::MemchrPrelude => "memchr_prelude",
            Pass::PtrCopy => "ptr_copy",
            Pass::MemMove => "mem_move",
            Pass::MemSet => "mem_set",
            Pass::MemCmp => "mem_cmp",
            Pass::ArrayElementPointerOrigin => "array_element_pointer_origin",
            Pass::ArrayElementPointerParamHoist => "array_element_pointer_param_hoist",
            Pass::BufferCursor => "buffer_cursor",
            Pass::AtomicLocals => "atomic_locals",
            Pass::LateInlineTemps => "late_inline_temps",
            Pass::AtomicCompareExchange => "atomic_compare_exchange",
            Pass::AssertRecovery => "assert_recovery",
            Pass::VarAliases => "var_aliases",
            Pass::ConstantConditions => "constant_conditions",
            Pass::LibcExit => "libc_exit",
            Pass::PruneUnusedDefinitions => "prune_unused_definitions",
            Pass::SetjmpRecovery => "setjmp_recovery",
            Pass::UnusedItems => "unused_items",
            Pass::UnusedParams => "unused_params",
            Pass::FinalReturns => "final_returns",
            Pass::MainZeroExit => "main_zero_exit",
        }
    }

    pub fn parse(name: &str) -> Option<Self> {
        Some(match name {
            "goto" => Pass::Goto,
            "switch" => Pass::Switch,
            "early_inline_temps" => Pass::EarlyInlineTemps,
            "anonymous_structs" => Pass::AnonymousStructs,
            "param_spills" => Pass::ParamSpills,
            "zero_init" => Pass::ZeroInit,
            "struct_field_init" => Pass::StructFieldInit,
            "singleton_scopes" => Pass::SingletonScopes,
            "compound_assign" => Pass::CompoundAssign,
            "swap" => Pass::Swap,
            "for_continue" => Pass::ForContinue,
            "constant_index_casts" => Pass::ConstantIndexCasts,
            "unnecessary_casts" => Pass::UnnecessaryCasts,
            "call_args" => Pass::CallArgs,
            "retval" => Pass::Retval,
            "final_return_temps" => Pass::FinalReturnTemps,
            "lazy_singleton" => Pass::LazySingleton,
            "drop_call_results" => Pass::DropCallResults,
            "string_lift" => Pass::StringLift,
            "string_params" => Pass::StringParams,
            "ptr_len" => Pass::PtrLen,
            "slice_index" => Pass::SliceIndex,
            "slice_loop" => Pass::SliceLoop,
            "slice_swap" => Pass::SliceSwap,
            "slice_reduce" => Pass::SliceReduce,
            "range_loop" => Pass::RangeLoop,
            "va_list" => Pass::VaList,
            "remove_mut" => Pass::RemoveMut,
            "string_copy" => Pass::StringCopy,
            "string_libc" => Pass::StringLibc,
            "ctype_libc" => Pass::CTypeLibc,
            "sort_search" => Pass::SortSearch,
            "heap_ownership" => Pass::HeapOwnership,
            "option_box_locals" => Pass::OptionBoxLocals,
            "interprocedural_alloc_promotion" => Pass::InterproceduralAllocPromotion,
            "dead_locals" => Pass::DeadLocals,
            "sprintf_format" => Pass::SprintfFormat,
            "printf_format" => Pass::PrintfFormat,
            "printf_stream" => Pass::PrintfStream,
            "c_strings" => Pass::CStrings,
            "stdio" => Pass::Stdio,
            "perror" => Pass::Perror,
            "memchr_prelude::fixup_calls" => Pass::MemchrPreludeFixupCalls,
            "nullable_pointer" => Pass::NullablePointer,
            "string_lift::fixup_c_strings" => Pass::StringLiftFixupCStrings,
            "memchr_prelude" => Pass::MemchrPrelude,
            "ptr_copy" => Pass::PtrCopy,
            "mem_move" => Pass::MemMove,
            "mem_set" => Pass::MemSet,
            "mem_cmp" => Pass::MemCmp,
            "array_element_pointer_origin" => Pass::ArrayElementPointerOrigin,
            "array_element_pointer_param_hoist" => Pass::ArrayElementPointerParamHoist,
            "buffer_cursor" => Pass::BufferCursor,
            "atomic_locals" => Pass::AtomicLocals,
            "late_inline_temps" => Pass::LateInlineTemps,
            "atomic_compare_exchange" => Pass::AtomicCompareExchange,
            "assert_recovery" => Pass::AssertRecovery,
            "var_aliases" => Pass::VarAliases,
            "constant_conditions" => Pass::ConstantConditions,
            "libc_exit" => Pass::LibcExit,
            "prune_unused_definitions" => Pass::PruneUnusedDefinitions,
            "setjmp_recovery" => Pass::SetjmpRecovery,
            "unused_items" => Pass::UnusedItems,
            "unused_params" => Pass::UnusedParams,
            "final_returns" => Pass::FinalReturns,
            "main_zero_exit" => Pass::MainZeroExit,
            _ => return None,
        })
    }
}
