#ifndef _SLATE_BITS_DARWIN_UNISTD_H
#define _SLATE_BITS_DARWIN_UNISTD_H

#if !defined(_SLATE_LIBC)
#error "Never include <bits/darwin/unistd.h> directly; include a public header instead."
#endif

#define _PC_LINK_MAX               1
#define _PC_MAX_CANON              2
#define _PC_MAX_INPUT              3
#define _PC_NAME_MAX               4
#define _PC_PATH_MAX               5
#define _PC_PIPE_BUF               6
#define _PC_CHOWN_RESTRICTED       7
#define _PC_NO_TRUNC               8
#define _PC_VDISABLE               9
#define _PC_NAME_CHARS_MAX         10
#define _PC_CASE_SENSITIVE         11
#define _PC_CASE_PRESERVING        12

#define _SC_ARG_MAX                1
#define _SC_CHILD_MAX               2
#define _SC_CLK_TCK                  3
#define _SC_NGROUPS_MAX                4
#define _SC_OPEN_MAX                     5
#define _SC_JOB_CONTROL                    6
#define _SC_SAVED_IDS                        7
#define _SC_VERSION                            8
#define _SC_BC_BASE_MAX                          9
#define _SC_BC_DIM_MAX                              10
#define _SC_BC_SCALE_MAX                               11
#define _SC_BC_STRING_MAX                                 12
#define _SC_COLL_WEIGHTS_MAX                                 13
#define _SC_EXPR_NEST_MAX                                       14
#define _SC_LINE_MAX                                               15
#define _SC_RE_DUP_MAX                                                16
#define _SC_2_VERSION                                                    17
#define _SC_2_C_BIND                                                        18
#define _SC_2_C_DEV                                                            19
#define _SC_2_CHAR_TERM                                                           20
#define _SC_2_FORT_DEV                                                               21
#define _SC_2_FORT_RUN                                                                  22
#define _SC_2_LOCALEDEF                                                                    23
#define _SC_2_SW_DEV                                                                          24
#define _SC_2_UPE                                                                                25
#define _SC_STREAM_MAX                                                                              26
#define _SC_TZNAME_MAX                                                                                 27
#define _SC_ASYNCHRONOUS_IO                                                                                28
#define _SC_PAGESIZE                                                                                         29
#define _SC_PAGE_SIZE               _SC_PAGESIZE
#define _SC_MEMLOCK                                                                                             30
#define _SC_MEMLOCK_RANGE                                                                                          31
#define _SC_MEMORY_PROTECTION                                                                                        32
#define _SC_MESSAGE_PASSING                                                                                             33
#define _SC_PRIORITIZED_IO                                                                                                 34
#define _SC_PRIORITY_SCHEDULING                                                                                               35
#define _SC_REALTIME_SIGNALS                                                                                                     36
#define _SC_SEMAPHORES                                                                                                              37
#define _SC_FSYNC                                                                                                                     38
#define _SC_SHARED_MEMORY_OBJECTS                                                                                                        39
#define _SC_SYNCHRONIZED_IO                                                                                                                 40
#define _SC_TIMERS                                                                                                                             41
#define _SC_AIO_LISTIO_MAX                                                                                                                        42
#define _SC_AIO_MAX                                                                                                                                  43
#define _SC_AIO_PRIO_DELTA_MAX                                                                                                                          44
#define _SC_DELAYTIMER_MAX                                                                                                                                 45
#define _SC_MQ_OPEN_MAX                                                                                                                                       46
#define _SC_MAPPED_FILES                                                                                                                                        47
#define _SC_RTSIG_MAX                                                                                                                                              48
#define _SC_SEM_NSEMS_MAX                                                                                                                                             49
#define _SC_SEM_VALUE_MAX                                                                                                                                                50
#define _SC_SIGQUEUE_MAX                                                                                                                                                    51
#define _SC_TIMER_MAX                                                                                                                                                          52
#define _SC_NPROCESSORS_CONF        57
#define _SC_NPROCESSORS_ONLN        58
#define _SC_2_PBS                   59
#define _SC_2_PBS_ACCOUNTING        60
#define _SC_2_PBS_CHECKPOINT        61
#define _SC_2_PBS_LOCATE            62
#define _SC_2_PBS_MESSAGE           63
#define _SC_2_PBS_TRACK             64
#define _SC_ADVISORY_INFO           65
#define _SC_BARRIERS                66
#define _SC_CLOCK_SELECTION         67
#define _SC_CPUTIME                 68
#define _SC_FILE_LOCKING            69
#define _SC_GETGR_R_SIZE_MAX        70
#define _SC_GETPW_R_SIZE_MAX        71
#define _SC_HOST_NAME_MAX           72
#define _SC_LOGIN_NAME_MAX          73
#define _SC_MONOTONIC_CLOCK         74
#define _SC_MQ_PRIO_MAX             75
#define _SC_READER_WRITER_LOCKS     76
#define _SC_REGEXP                  77
#define _SC_SHELL                   78
#define _SC_SPAWN                   79
#define _SC_SPIN_LOCKS              80
#define _SC_SPORADIC_SERVER         81
#define _SC_THREAD_ATTR_STACKADDR   82
#define _SC_THREAD_ATTR_STACKSIZE   83
#define _SC_THREAD_CPUTIME          84
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 85
#define _SC_THREAD_KEYS_MAX         86
#define _SC_THREAD_PRIO_INHERIT     87
#define _SC_THREAD_PRIO_PROTECT     88
#define _SC_THREAD_PRIORITY_SCHEDULING 89
#define _SC_THREAD_PROCESS_SHARED   90
#define _SC_THREAD_SAFE_FUNCTIONS   91
#define _SC_THREAD_SPORADIC_SERVER  92
#define _SC_THREAD_STACK_MIN        93
#define _SC_THREAD_THREADS_MAX      94
#define _SC_TIMEOUTS                95
#define _SC_THREADS                 96
#define _SC_TRACE                   97
#define _SC_TRACE_EVENT_FILTER      98
#define _SC_TRACE_EVENT_NAME_MAX    99
#define _SC_TRACE_INHERIT           100
#define _SC_TRACE_LOG               101
#define _SC_TRACE_NAME_MAX          102
#define _SC_TRACE_SYS_MAX           103
#define _SC_TRACE_USER_EVENT_MAX    104
#define _SC_TTY_NAME_MAX            105
#define _SC_TYPED_MEMORY_OBJECTS    106
#define _SC_V6_ILP32_OFF32          107
#define _SC_V6_ILP32_OFFBIG         108
#define _SC_V6_LP64_OFF64           109
#define _SC_V6_LPBIG_OFFBIG         110
#define _SC_V7_ILP32_OFF32          111
#define _SC_V7_ILP32_OFFBIG         112
#define _SC_V7_LP64_OFF64           113
#define _SC_V7_LPBIG_OFFBIG         114
#define _SC_XOPEN_CRYPT             115
#define _SC_XOPEN_ENH_I18N          116
#define _SC_XOPEN_LEGACY            117
#define _SC_XOPEN_REALTIME          118
#define _SC_XOPEN_REALTIME_THREADS  119
#define _SC_XOPEN_SHM               120
#define _SC_XOPEN_STREAMS           121
#define _SC_XOPEN_UNIX              122
#define _SC_XOPEN_VERSION           123
#define _SC_XOPEN_XCU_VERSION       124
#define _SC_ATEXIT_MAX               125
#define _SC_IPV6                    126
#define _SC_RAW_SOCKETS             127
#define _SC_SYMLOOP_MAX              128

#endif
