//! The parsed CIR, kept as a generic MLIR Op-tree rather than a typed enum. The
//! generic form `%res = "name"(%operands) <{attrs}> ({regions}) : (types) -> types`
//! is completely op-agnostic, so this model stays stable as op coverage grows;
//! lowering interprets `op.name` and reads attrs/operands through typed views.

use std::collections::BTreeMap;

/// A whole translation unit: the top-level ops (a `builtin.module` and its body).
#[derive(Debug, Default, Clone)]
pub struct Module {
    pub ops: Vec<Op>,
    pub aliases: BTreeMap<String, String>,
}

/// One MLIR operation in generic form.
#[derive(Debug, Clone)]
pub struct Op {
    /// SSA results this op defines, e.g. `%3`, `%c` (names without the `%`).
    pub results: Vec<String>,
    /// Dialect-qualified op name, e.g. `cir.const`, `cir.binop`, `cir.func`.
    pub name: String,
    /// SSA operands referenced (names without the `%`).
    pub operands: Vec<String>,
    /// Successor block labels from a `[^bbN, ...]` list (names without the `^`).
    pub successors: Vec<String>,
    /// `<{...}>` inherent attributes plus `{...}` discardable attributes, merged.
    pub attrs: BTreeMap<String, Attr>,
    /// Nested regions `({ ... })`.
    pub regions: Vec<Region>,
    /// Functional type signature `: (a, b) -> r`, kept as raw text for V0.
    pub ty: Option<String>,
    /// Trailing `loc(...)`, kept verbatim for the source-location join.
    pub loc: Option<String>,
}

impl Op {
    pub fn kind(&self) -> CirOpKind {
        CirOpKind::parse(&self.name)
    }
}

#[derive(Debug, Default, Clone)]
pub struct Region {
    pub blocks: Vec<Block>,
}

#[derive(Debug, Default, Clone)]
pub struct Block {
    pub label: Option<String>,
    pub args: Vec<(String, String)>,
    pub ops: Vec<Op>,
}

#[derive(Debug, Clone)]
pub enum Attr {
    Raw(String),
    Int(i64),
    Str(String),
    Type(String),
    Array(Vec<Attr>),
    Dict,
}

impl Attr {
    pub fn as_int(&self) -> Option<i64> {
        match self {
            Attr::Int(n) => Some(*n),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Attr::Str(s) | Attr::Raw(s) | Attr::Type(s) => Some(s),
            _ => None,
        }
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CirOpKind {
    Abs,
    Acos,
    Add,
    AddOverflow,
    Alloca,
    And,
    Asin,
    Asm,
    Assume,
    Atan,
    Atan2,
    AtomicCmpxchg,
    AtomicClear,
    AtomicFence,
    AtomicFetch,
    AtomicTestAndSet,
    AtomicXchg,
    Bitreverse,
    BlockAddress,
    Br,
    Brcond,
    Break,
    ByteSwap,
    Call,
    CallLlvmIntrinsic,
    Case,
    Cast,
    Ceil,
    ClearCache,
    CleanupScope,
    Clrsb,
    Clz,
    Cmp,
    ComplexAdd,
    ComplexConj,
    ComplexCreate,
    ComplexDiv,
    ComplexImag,
    ComplexImagPtr,
    ComplexMul,
    ComplexReal,
    ComplexRealPtr,
    ComplexSub,
    Condition,
    Const,
    Continue,
    Copy,
    Copysign,
    Cos,
    Ctz,
    Dec,
    Div,
    DivOverflow,
    Do,
    EhSetjmp,
    Exp,
    Exp2,
    Expect,
    ExtractMember,
    Fabs,
    Fadd,
    Fdiv,
    Ffs,
    Floor,
    Fma,
    Fmaximum,
    Fmaxnum,
    Fminimum,
    Fminnum,
    Fmod,
    Fmul,
    Fneg,
    For,
    FrameAddress,
    Fsub,
    Func,
    GetBitfield,
    GetElement,
    GetGlobal,
    GetMember,
    Global,
    Goto,
    If,
    Inc,
    IndirectBr,
    InsertMember,
    IsConstant,
    IsFpClass,
    Label,
    LibcMemchr,
    LibcMemcpy,
    LibcMemmove,
    LibcMemset,
    Llrint,
    Llround,
    Load,
    Log,
    Log10,
    Log2,
    Lrint,
    Lround,
    Minus,
    Modf,
    Mul,
    MulOverflow,
    Nearbyint,
    Not,
    Objsize,
    Or,
    Parity,
    Popcount,
    Pow,
    Prefetch,
    PtrDiff,
    PtrStride,
    Rem,
    RemOverflow,
    Return,
    ReturnAddress,
    Rint,
    Rotate,
    Round,
    Roundeven,
    Scope,
    Select,
    SetBitfield,
    Shift,
    Signbit,
    Sin,
    Sqrt,
    Stackrestore,
    Stacksave,
    Store,
    Sub,
    SubOverflow,
    Switch,
    SwitchFlat,
    Tan,
    Ternary,
    Trap,
    Triple,
    Trunc,
    Unreachable,
    VaArg,
    VaEnd,
    VaStart,
    VecExtract,
    VecInsert,
    VecShuffle,
    While,
    Xor,
    Yield,
    Other(String),
}

impl CirOpKind {
    pub fn parse(name: &str) -> CirOpKind {
        match name {
            "cir.abs" => CirOpKind::Abs,
            "cir.acos" => CirOpKind::Acos,
            "cir.add" => CirOpKind::Add,
            "cir.add.overflow" => CirOpKind::AddOverflow,
            "cir.alloca" => CirOpKind::Alloca,
            "cir.and" => CirOpKind::And,
            "cir.asin" => CirOpKind::Asin,
            "cir.asm" => CirOpKind::Asm,
            "cir.assume" => CirOpKind::Assume,
            "cir.atan" => CirOpKind::Atan,
            "cir.atan2" => CirOpKind::Atan2,
            "cir.atomic.cmpxchg" => CirOpKind::AtomicCmpxchg,
            "cir.atomic.clear" => CirOpKind::AtomicClear,
            "cir.atomic.fence" => CirOpKind::AtomicFence,
            "cir.atomic.fetch" => CirOpKind::AtomicFetch,
            "cir.atomic.test_and_set" => CirOpKind::AtomicTestAndSet,
            "cir.atomic.xchg" => CirOpKind::AtomicXchg,
            "cir.bitreverse" => CirOpKind::Bitreverse,
            "cir.block_address" => CirOpKind::BlockAddress,
            "cir.br" => CirOpKind::Br,
            "cir.brcond" => CirOpKind::Brcond,
            "cir.break" => CirOpKind::Break,
            "cir.byte_swap" => CirOpKind::ByteSwap,
            "cir.call" => CirOpKind::Call,
            "cir.call_llvm_intrinsic" => CirOpKind::CallLlvmIntrinsic,
            "cir.case" => CirOpKind::Case,
            "cir.cast" => CirOpKind::Cast,
            "cir.ceil" => CirOpKind::Ceil,
            "cir.clear_cache" => CirOpKind::ClearCache,
            "cir.cleanup.scope" => CirOpKind::CleanupScope,
            "cir.clrsb" => CirOpKind::Clrsb,
            "cir.clz" => CirOpKind::Clz,
            "cir.cmp" => CirOpKind::Cmp,
            "cir.complex.add" => CirOpKind::ComplexAdd,
            "cir.complex.conj" => CirOpKind::ComplexConj,
            "cir.complex.create" => CirOpKind::ComplexCreate,
            "cir.complex.div" => CirOpKind::ComplexDiv,
            "cir.complex.imag" => CirOpKind::ComplexImag,
            "cir.complex.imag_ptr" => CirOpKind::ComplexImagPtr,
            "cir.complex.mul" => CirOpKind::ComplexMul,
            "cir.complex.real" => CirOpKind::ComplexReal,
            "cir.complex.real_ptr" => CirOpKind::ComplexRealPtr,
            "cir.complex.sub" => CirOpKind::ComplexSub,
            "cir.condition" => CirOpKind::Condition,
            "cir.const" => CirOpKind::Const,
            "cir.continue" => CirOpKind::Continue,
            "cir.copy" => CirOpKind::Copy,
            "cir.copysign" => CirOpKind::Copysign,
            "cir.cos" => CirOpKind::Cos,
            "cir.ctz" => CirOpKind::Ctz,
            "cir.dec" => CirOpKind::Dec,
            "cir.div" => CirOpKind::Div,
            "cir.div.overflow" => CirOpKind::DivOverflow,
            "cir.do" => CirOpKind::Do,
            "cir.eh.setjmp" => CirOpKind::EhSetjmp,
            "cir.exp" => CirOpKind::Exp,
            "cir.exp2" => CirOpKind::Exp2,
            "cir.expect" => CirOpKind::Expect,
            "cir.extract_member" => CirOpKind::ExtractMember,
            "cir.fabs" => CirOpKind::Fabs,
            "cir.fadd" => CirOpKind::Fadd,
            "cir.fdiv" => CirOpKind::Fdiv,
            "cir.ffs" => CirOpKind::Ffs,
            "cir.floor" => CirOpKind::Floor,
            "cir.fma" => CirOpKind::Fma,
            "cir.fmaximum" => CirOpKind::Fmaximum,
            "cir.fmaxnum" => CirOpKind::Fmaxnum,
            "cir.fminimum" => CirOpKind::Fminimum,
            "cir.fminnum" => CirOpKind::Fminnum,
            "cir.fmod" => CirOpKind::Fmod,
            "cir.fmul" => CirOpKind::Fmul,
            "cir.fmuladd" => CirOpKind::Fma,
            "cir.fneg" => CirOpKind::Fneg,
            "cir.for" => CirOpKind::For,
            "cir.frame_address" => CirOpKind::FrameAddress,
            "cir.fsub" => CirOpKind::Fsub,
            "cir.func" => CirOpKind::Func,
            "cir.get_bitfield" => CirOpKind::GetBitfield,
            "cir.get_element" => CirOpKind::GetElement,
            "cir.get_global" => CirOpKind::GetGlobal,
            "cir.get_member" => CirOpKind::GetMember,
            "cir.global" => CirOpKind::Global,
            "cir.goto" => CirOpKind::Goto,
            "cir.if" => CirOpKind::If,
            "cir.inc" => CirOpKind::Inc,
            "cir.indirect_br" | "cir.indirect_goto" => CirOpKind::IndirectBr,
            "cir.insert_member" => CirOpKind::InsertMember,
            "cir.is_constant" => CirOpKind::IsConstant,
            "cir.is_fp_class" => CirOpKind::IsFpClass,
            "cir.label" => CirOpKind::Label,
            "cir.libc.memchr" => CirOpKind::LibcMemchr,
            "cir.libc.memcpy" => CirOpKind::LibcMemcpy,
            "cir.libc.memmove" => CirOpKind::LibcMemmove,
            "cir.libc.memset" => CirOpKind::LibcMemset,
            "cir.llrint" => CirOpKind::Llrint,
            "cir.llround" => CirOpKind::Llround,
            "cir.load" => CirOpKind::Load,
            "cir.log" => CirOpKind::Log,
            "cir.log10" => CirOpKind::Log10,
            "cir.log2" => CirOpKind::Log2,
            "cir.lrint" => CirOpKind::Lrint,
            "cir.lround" => CirOpKind::Lround,
            "cir.minus" => CirOpKind::Minus,
            "cir.modf" => CirOpKind::Modf,
            "cir.mul" => CirOpKind::Mul,
            "cir.mul.overflow" => CirOpKind::MulOverflow,
            "cir.nearbyint" => CirOpKind::Nearbyint,
            "cir.not" => CirOpKind::Not,
            "cir.objsize" => CirOpKind::Objsize,
            "cir.or" => CirOpKind::Or,
            "cir.parity" => CirOpKind::Parity,
            "cir.popcount" => CirOpKind::Popcount,
            "cir.pow" => CirOpKind::Pow,
            "cir.prefetch" => CirOpKind::Prefetch,
            "cir.ptr_diff" => CirOpKind::PtrDiff,
            "cir.ptr_stride" => CirOpKind::PtrStride,
            "cir.rem" => CirOpKind::Rem,
            "cir.rem.overflow" => CirOpKind::RemOverflow,
            "cir.return" => CirOpKind::Return,
            "cir.return_address" => CirOpKind::ReturnAddress,
            "cir.rint" => CirOpKind::Rint,
            "cir.rotate" => CirOpKind::Rotate,
            "cir.round" => CirOpKind::Round,
            "cir.roundeven" => CirOpKind::Roundeven,
            "cir.scope" => CirOpKind::Scope,
            "cir.select" => CirOpKind::Select,
            "cir.set_bitfield" => CirOpKind::SetBitfield,
            "cir.shift" => CirOpKind::Shift,
            "cir.signbit" => CirOpKind::Signbit,
            "cir.sin" => CirOpKind::Sin,
            "cir.sqrt" => CirOpKind::Sqrt,
            "cir.stackrestore" => CirOpKind::Stackrestore,
            "cir.stacksave" => CirOpKind::Stacksave,
            "cir.store" => CirOpKind::Store,
            "cir.sub" => CirOpKind::Sub,
            "cir.sub.overflow" => CirOpKind::SubOverflow,
            "cir.switch" => CirOpKind::Switch,
            "cir.switch.flat" => CirOpKind::SwitchFlat,
            "cir.tan" => CirOpKind::Tan,
            "cir.ternary" => CirOpKind::Ternary,
            "cir.trap" => CirOpKind::Trap,
            "cir.triple" => CirOpKind::Triple,
            "cir.trunc" => CirOpKind::Trunc,
            "cir.unreachable" => CirOpKind::Unreachable,
            "cir.va_arg" => CirOpKind::VaArg,
            "cir.va_end" => CirOpKind::VaEnd,
            "cir.va_start" => CirOpKind::VaStart,
            "cir.vec.extract" => CirOpKind::VecExtract,
            "cir.vec.insert" => CirOpKind::VecInsert,
            "cir.vec.shuffle" => CirOpKind::VecShuffle,
            "cir.while" => CirOpKind::While,
            "cir.xor" => CirOpKind::Xor,
            "cir.yield" => CirOpKind::Yield,
            other => CirOpKind::Other(other.to_string()),
        }
    }
}
