//! The parsed CIR, re-exported from `clang-ir`'s generic MLIR op-tree rather
//! than a hand-rolled one. `clang-ir` owns the text parser and the typed
//! `Attribute`/`Type` representations; `CirOpKind` (Slate's own op-name
//! dispatch classifier) stays here since it's specific to how the lowerer
//! organizes its `cir.*` handlers, not something the generic op-tree needs.

pub use clang_ir::ast::{
    Attribute as Attr, Block, Module, Operation as Op, Region, Type as CirType,
};

/// Slate's op-name dispatch key. Lives here (not in `clang-ir`) because it's
/// keyed off exactly the `cir.*` handler split the lowerer uses, not a
/// general-purpose classification `clang-ir` itself would need.
pub trait OpKindExt {
    fn kind(&self) -> CirOpKind;
}

impl OpKindExt for Op {
    fn kind(&self) -> CirOpKind {
        CirOpKind::parse(&self.name)
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CirOpKind {
    Acos,
    Alloca,
    Asin,
    Asm,
    Atan,
    Atan2,
    Br,
    Brcond,
    Break,
    Call,
    CallLlvmIntrinsic,
    Case,
    CleanupScope,
    ComplexConj,
    ComplexDiv,
    ComplexMul,
    Condition,
    Const,
    Continue,
    Cos,
    DivOverflow,
    Do,
    Exp,
    Exp2,
    Expect,
    Fmaximum,
    Fminimum,
    Fmod,
    For,
    Func,
    GetBitfield,
    GetElement,
    GetGlobal,
    GetMember,
    Global,
    Goto,
    If,
    IndirectBr,
    InsertMember,
    Label,
    Llrint,
    Llround,
    Load,
    Log,
    Log10,
    Log2,
    Lrint,
    Lround,
    Pow,
    RemOverflow,
    Return,
    Roundeven,
    Scope,
    SetBitfield,
    Sin,
    Sqrt,
    Stackrestore,
    Store,
    Switch,
    SwitchFlat,
    Tan,
    Ternary,
    Trap,
    Triple,
    Unreachable,
    VaArg,
    VaCopy,
    VaStart,
    While,
    Yield,
    Other(String),
}

impl CirOpKind {
    pub fn parse(name: &str) -> CirOpKind {
        match name {
            "cir.acos" => CirOpKind::Acos,
            "cir.alloca" => CirOpKind::Alloca,
            "cir.asin" => CirOpKind::Asin,
            "cir.asm" => CirOpKind::Asm,
            "cir.atan" => CirOpKind::Atan,
            "cir.atan2" => CirOpKind::Atan2,
            "cir.br" => CirOpKind::Br,
            "cir.brcond" => CirOpKind::Brcond,
            "cir.break" => CirOpKind::Break,
            "cir.call" => CirOpKind::Call,
            "cir.call_llvm_intrinsic" => CirOpKind::CallLlvmIntrinsic,
            "cir.case" => CirOpKind::Case,
            "cir.cleanup.scope" => CirOpKind::CleanupScope,
            "cir.complex.conj" => CirOpKind::ComplexConj,
            "cir.complex.div" => CirOpKind::ComplexDiv,
            "cir.complex.mul" => CirOpKind::ComplexMul,
            "cir.condition" => CirOpKind::Condition,
            "cir.const" => CirOpKind::Const,
            "cir.continue" => CirOpKind::Continue,
            "cir.cos" => CirOpKind::Cos,
            "cir.div.overflow" => CirOpKind::DivOverflow,
            "cir.do" => CirOpKind::Do,
            "cir.exp" => CirOpKind::Exp,
            "cir.exp2" => CirOpKind::Exp2,
            "cir.expect" => CirOpKind::Expect,
            "cir.fmaximum" => CirOpKind::Fmaximum,
            "cir.fminimum" => CirOpKind::Fminimum,
            "cir.fmod" => CirOpKind::Fmod,
            "cir.for" => CirOpKind::For,
            "cir.func" => CirOpKind::Func,
            "cir.get_bitfield" => CirOpKind::GetBitfield,
            "cir.get_element" => CirOpKind::GetElement,
            "cir.get_global" => CirOpKind::GetGlobal,
            "cir.get_member" => CirOpKind::GetMember,
            "cir.global" => CirOpKind::Global,
            "cir.goto" => CirOpKind::Goto,
            "cir.if" => CirOpKind::If,
            "cir.indirect_br" | "cir.indirect_goto" => CirOpKind::IndirectBr,
            "cir.insert_member" => CirOpKind::InsertMember,
            "cir.label" => CirOpKind::Label,
            "cir.llrint" => CirOpKind::Llrint,
            "cir.llround" => CirOpKind::Llround,
            "cir.load" => CirOpKind::Load,
            "cir.log" => CirOpKind::Log,
            "cir.log10" => CirOpKind::Log10,
            "cir.log2" => CirOpKind::Log2,
            "cir.lrint" => CirOpKind::Lrint,
            "cir.lround" => CirOpKind::Lround,
            "cir.pow" => CirOpKind::Pow,
            "cir.rem.overflow" => CirOpKind::RemOverflow,
            "cir.return" => CirOpKind::Return,
            "cir.roundeven" => CirOpKind::Roundeven,
            "cir.scope" => CirOpKind::Scope,
            "cir.set_bitfield" => CirOpKind::SetBitfield,
            "cir.sin" => CirOpKind::Sin,
            "cir.sqrt" => CirOpKind::Sqrt,
            "cir.stackrestore" => CirOpKind::Stackrestore,
            "cir.store" => CirOpKind::Store,
            "cir.switch" => CirOpKind::Switch,
            "cir.switch.flat" => CirOpKind::SwitchFlat,
            "cir.tan" => CirOpKind::Tan,
            "cir.ternary" => CirOpKind::Ternary,
            "cir.trap" => CirOpKind::Trap,
            "cir.triple" => CirOpKind::Triple,
            "cir.unreachable" => CirOpKind::Unreachable,
            "cir.va_arg" => CirOpKind::VaArg,
            "cir.va_copy" => CirOpKind::VaCopy,
            "cir.va_start" => CirOpKind::VaStart,
            "cir.while" => CirOpKind::While,
            "cir.yield" => CirOpKind::Yield,
            other => CirOpKind::Other(other.to_string()),
        }
    }
}
