#ifndef _SLATE_SCSI_IOCTL_H
#define _SLATE_SCSI_IOCTL_H
enum {
  SCSI_IOCTL_SEND_COMMAND      = 1,
  SCSI_IOCTL_TEST_UNIT_READY   = 2,
  SCSI_IOCTL_BENCHMARK_COMMAND = 3,
  SCSI_IOCTL_SYNC              = 4,
  SCSI_IOCTL_START_UNIT        = 5,
  SCSI_IOCTL_STOP_UNIT         = 6,
  SCSI_IOCTL_DOORLOCK          = 0x5380,
  SCSI_IOCTL_DOORUNLOCK        = 0x5381,
};
#endif
