//! The parsed CIR, re-exported from `clang-ir`'s generic MLIR op-tree rather
//! than a hand-rolled one. `clang-ir` owns the text parser and the typed
//! `Attribute`/`Type` representations; `CirOpKind` (Slate's own op-name
//! dispatch classifier) stays here since it's specific to how the lowerer
//! organizes its `cir.*` handlers, not something the generic op-tree needs.

pub use clang_ir::ast::{Attribute as Attr, Block, Module, Operation as Op, Region, Type as CirType};

/// Slate's op-name dispatch key. Lives here (not in `clang-ir`) because it's
/// keyed off exactly the `cir.*` handler split the lowerer uses, not a
/// general-purpose classification `clang-ir` itself would need.
pub trait OpKindExt {
    fn kind(&self) -> CirOpKind;
}

impl OpKindExt for Op {
    fn kind(&self) -> CirOpKind {
        CirOpKind::parse(&self.name)
    }
}

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CirOpKind {
    Abs,
    Acos,
    Add,
    AddOverflow,
    Alloca,
    And,
    Asin,
    Asm,
    Assume,
    Atan,
    Atan2,
    AtomicCmpxchg,
    AtomicClear,
    AtomicFence,
    AtomicFetch,
    AtomicTestAndSet,
    AtomicXchg,
    Bitreverse,
    BlockAddress,
    Br,
    Brcond,
    Break,
    ByteSwap,
    Call,
    CallLlvmIntrinsic,
    Case,
    Cast,
    Ceil,
    ClearCache,
    CleanupScope,
    Clrsb,
    Clz,
    Cmp,
    ComplexAdd,
    ComplexConj,
    ComplexCreate,
    ComplexDiv,
    ComplexImag,
    ComplexImagPtr,
    ComplexMul,
    ComplexReal,
    ComplexRealPtr,
    ComplexSub,
    Condition,
    Const,
    Continue,
    Copy,
    Copysign,
    Cos,
    Ctz,
    Dec,
    Div,
    DivOverflow,
    Do,
    EhSetjmp,
    Exp,
    Exp2,
    Expect,
    ExtractMember,
    Fabs,
    Fadd,
    Fdiv,
    Ffs,
    Floor,
    Fma,
    Fmaximum,
    Fmaxnum,
    Fminimum,
    Fminnum,
    Fmod,
    Fmul,
    Fneg,
    For,
    FrameAddress,
    Fsub,
    Func,
    GetBitfield,
    GetElement,
    GetGlobal,
    GetMember,
    Global,
    Goto,
    If,
    Inc,
    IndirectBr,
    InsertMember,
    IsConstant,
    IsFpClass,
    Label,
    LibcMemchr,
    LibcMemcpy,
    LibcMemmove,
    LibcMemset,
    Llrint,
    Llround,
    Load,
    Log,
    Log10,
    Log2,
    Lrint,
    Lround,
    Minus,
    Modf,
    Mul,
    MulOverflow,
    Nearbyint,
    Not,
    Objsize,
    Or,
    Parity,
    Popcount,
    Pow,
    Prefetch,
    PtrDiff,
    PtrStride,
    Rem,
    RemOverflow,
    Return,
    ReturnAddress,
    Rint,
    Rotate,
    Round,
    Roundeven,
    Scope,
    Select,
    SetBitfield,
    Shift,
    Signbit,
    Sin,
    Sqrt,
    Stackrestore,
    Stacksave,
    Store,
    Sub,
    SubOverflow,
    Switch,
    SwitchFlat,
    Tan,
    Ternary,
    Trap,
    Triple,
    Trunc,
    Unreachable,
    VaArg,
    VaCopy,
    VaEnd,
    VaStart,
    VecCmp,
    VecCreate,
    VecExtract,
    VecInsert,
    VecShuffle,
    VecSplat,
    While,
    Xor,
    Yield,
    Other(String),
}

impl CirOpKind {
    pub fn parse(name: &str) -> CirOpKind {
        match name {
            "cir.abs" => CirOpKind::Abs,
            "cir.acos" => CirOpKind::Acos,
            "cir.add" => CirOpKind::Add,
            "cir.add.overflow" => CirOpKind::AddOverflow,
            "cir.alloca" => CirOpKind::Alloca,
            "cir.and" => CirOpKind::And,
            "cir.asin" => CirOpKind::Asin,
            "cir.asm" => CirOpKind::Asm,
            "cir.assume" => CirOpKind::Assume,
            "cir.atan" => CirOpKind::Atan,
            "cir.atan2" => CirOpKind::Atan2,
            "cir.atomic.cmpxchg" => CirOpKind::AtomicCmpxchg,
            "cir.atomic.clear" => CirOpKind::AtomicClear,
            "cir.atomic.fence" => CirOpKind::AtomicFence,
            "cir.atomic.fetch" => CirOpKind::AtomicFetch,
            "cir.atomic.test_and_set" => CirOpKind::AtomicTestAndSet,
            "cir.atomic.xchg" => CirOpKind::AtomicXchg,
            "cir.bitreverse" => CirOpKind::Bitreverse,
            "cir.block_address" => CirOpKind::BlockAddress,
            "cir.br" => CirOpKind::Br,
            "cir.brcond" => CirOpKind::Brcond,
            "cir.break" => CirOpKind::Break,
            "cir.byte_swap" => CirOpKind::ByteSwap,
            "cir.call" => CirOpKind::Call,
            "cir.call_llvm_intrinsic" => CirOpKind::CallLlvmIntrinsic,
            "cir.case" => CirOpKind::Case,
            "cir.cast" => CirOpKind::Cast,
            "cir.ceil" => CirOpKind::Ceil,
            "cir.clear_cache" => CirOpKind::ClearCache,
            "cir.cleanup.scope" => CirOpKind::CleanupScope,
            "cir.clrsb" => CirOpKind::Clrsb,
            "cir.clz" => CirOpKind::Clz,
            "cir.cmp" => CirOpKind::Cmp,
            "cir.complex.add" => CirOpKind::ComplexAdd,
            "cir.complex.conj" => CirOpKind::ComplexConj,
            "cir.complex.create" => CirOpKind::ComplexCreate,
            "cir.complex.div" => CirOpKind::ComplexDiv,
            "cir.complex.imag" => CirOpKind::ComplexImag,
            "cir.complex.imag_ptr" => CirOpKind::ComplexImagPtr,
            "cir.complex.mul" => CirOpKind::ComplexMul,
            "cir.complex.real" => CirOpKind::ComplexReal,
            "cir.complex.real_ptr" => CirOpKind::ComplexRealPtr,
            "cir.complex.sub" => CirOpKind::ComplexSub,
            "cir.condition" => CirOpKind::Condition,
            "cir.const" => CirOpKind::Const,
            "cir.continue" => CirOpKind::Continue,
            "cir.copy" => CirOpKind::Copy,
            "cir.copysign" => CirOpKind::Copysign,
            "cir.cos" => CirOpKind::Cos,
            "cir.ctz" => CirOpKind::Ctz,
            "cir.dec" => CirOpKind::Dec,
            "cir.div" => CirOpKind::Div,
            "cir.div.overflow" => CirOpKind::DivOverflow,
            "cir.do" => CirOpKind::Do,
            "cir.eh.setjmp" => CirOpKind::EhSetjmp,
            "cir.exp" => CirOpKind::Exp,
            "cir.exp2" => CirOpKind::Exp2,
            "cir.expect" => CirOpKind::Expect,
            "cir.extract_member" => CirOpKind::ExtractMember,
            "cir.fabs" => CirOpKind::Fabs,
            "cir.fadd" => CirOpKind::Fadd,
            "cir.fdiv" => CirOpKind::Fdiv,
            "cir.ffs" => CirOpKind::Ffs,
            "cir.floor" => CirOpKind::Floor,
            "cir.fma" => CirOpKind::Fma,
            "cir.fmaximum" => CirOpKind::Fmaximum,
            "cir.fmaxnum" => CirOpKind::Fmaxnum,
            "cir.fminimum" => CirOpKind::Fminimum,
            "cir.fminnum" => CirOpKind::Fminnum,
            "cir.fmod" => CirOpKind::Fmod,
            "cir.fmul" => CirOpKind::Fmul,
            "cir.fmuladd" => CirOpKind::Fma,
            "cir.fneg" => CirOpKind::Fneg,
            "cir.for" => CirOpKind::For,
            "cir.frame_address" => CirOpKind::FrameAddress,
            "cir.fsub" => CirOpKind::Fsub,
            "cir.func" => CirOpKind::Func,
            "cir.get_bitfield" => CirOpKind::GetBitfield,
            "cir.get_element" => CirOpKind::GetElement,
            "cir.get_global" => CirOpKind::GetGlobal,
            "cir.get_member" => CirOpKind::GetMember,
            "cir.global" => CirOpKind::Global,
            "cir.goto" => CirOpKind::Goto,
            "cir.if" => CirOpKind::If,
            "cir.inc" => CirOpKind::Inc,
            "cir.indirect_br" | "cir.indirect_goto" => CirOpKind::IndirectBr,
            "cir.insert_member" => CirOpKind::InsertMember,
            "cir.is_constant" => CirOpKind::IsConstant,
            "cir.is_fp_class" => CirOpKind::IsFpClass,
            "cir.label" => CirOpKind::Label,
            "cir.libc.memchr" => CirOpKind::LibcMemchr,
            "cir.libc.memcpy" => CirOpKind::LibcMemcpy,
            "cir.libc.memmove" => CirOpKind::LibcMemmove,
            "cir.libc.memset" => CirOpKind::LibcMemset,
            "cir.llrint" => CirOpKind::Llrint,
            "cir.llround" => CirOpKind::Llround,
            "cir.load" => CirOpKind::Load,
            "cir.log" => CirOpKind::Log,
            "cir.log10" => CirOpKind::Log10,
            "cir.log2" => CirOpKind::Log2,
            "cir.lrint" => CirOpKind::Lrint,
            "cir.lround" => CirOpKind::Lround,
            "cir.minus" => CirOpKind::Minus,
            "cir.modf" => CirOpKind::Modf,
            "cir.mul" => CirOpKind::Mul,
            "cir.mul.overflow" => CirOpKind::MulOverflow,
            "cir.nearbyint" => CirOpKind::Nearbyint,
            "cir.not" => CirOpKind::Not,
            "cir.objsize" => CirOpKind::Objsize,
            "cir.or" => CirOpKind::Or,
            "cir.parity" => CirOpKind::Parity,
            "cir.popcount" => CirOpKind::Popcount,
            "cir.pow" => CirOpKind::Pow,
            "cir.prefetch" => CirOpKind::Prefetch,
            "cir.ptr_diff" => CirOpKind::PtrDiff,
            "cir.ptr_stride" => CirOpKind::PtrStride,
            "cir.rem" => CirOpKind::Rem,
            "cir.rem.overflow" => CirOpKind::RemOverflow,
            "cir.return" => CirOpKind::Return,
            "cir.return_address" => CirOpKind::ReturnAddress,
            "cir.rint" => CirOpKind::Rint,
            "cir.rotate" => CirOpKind::Rotate,
            "cir.round" => CirOpKind::Round,
            "cir.roundeven" => CirOpKind::Roundeven,
            "cir.scope" => CirOpKind::Scope,
            "cir.select" => CirOpKind::Select,
            "cir.set_bitfield" => CirOpKind::SetBitfield,
            "cir.shift" => CirOpKind::Shift,
            "cir.signbit" => CirOpKind::Signbit,
            "cir.sin" => CirOpKind::Sin,
            "cir.sqrt" => CirOpKind::Sqrt,
            "cir.stackrestore" => CirOpKind::Stackrestore,
            "cir.stacksave" => CirOpKind::Stacksave,
            "cir.store" => CirOpKind::Store,
            "cir.sub" => CirOpKind::Sub,
            "cir.sub.overflow" => CirOpKind::SubOverflow,
            "cir.switch" => CirOpKind::Switch,
            "cir.switch.flat" => CirOpKind::SwitchFlat,
            "cir.tan" => CirOpKind::Tan,
            "cir.ternary" => CirOpKind::Ternary,
            "cir.trap" => CirOpKind::Trap,
            "cir.triple" => CirOpKind::Triple,
            "cir.trunc" => CirOpKind::Trunc,
            "cir.unreachable" => CirOpKind::Unreachable,
            "cir.va_arg" => CirOpKind::VaArg,
            "cir.va_copy" => CirOpKind::VaCopy,
            "cir.va_end" => CirOpKind::VaEnd,
            "cir.va_start" => CirOpKind::VaStart,
            "cir.vec.cmp" => CirOpKind::VecCmp,
            "cir.vec.create" => CirOpKind::VecCreate,
            "cir.vec.extract" => CirOpKind::VecExtract,
            "cir.vec.insert" => CirOpKind::VecInsert,
            "cir.vec.shuffle" => CirOpKind::VecShuffle,
            "cir.vec.splat" => CirOpKind::VecSplat,
            "cir.while" => CirOpKind::While,
            "cir.xor" => CirOpKind::Xor,
            "cir.yield" => CirOpKind::Yield,
            other => CirOpKind::Other(other.to_string()),
        }
    }
}
