[package]
name = "slate-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
custom_debug.workspace = true
directories.workspace = true
foldhash.workspace = true
libc.workspace = true
miette.workspace = true
num-bigint.workspace = true
rustc_apfloat.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
clang-ast.workspace = true
tempfile.workspace = true
libtest-mimic.workspace = true

[lints.clippy]
large_enum_variant = "allow"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
result_large_err = "allow"

[[test]]
name = "filecheck"
harness = false
