[profile.slate]
default-filter = 'package(slate-c2rust)'

[profile.parser]
default-filter = 'package(slate-parser)'

[[profile.default.overrides]]
filter = 'test(gcc_torture_supported_tests_match_c)'
threads-required = "num-test-threads"
priority = 100

[[profile.default.overrides]]
filter = 'test(generated_differential)'
priority = 90

[[profile.default.overrides]]
filter = 'test(c_testsuite_supported_tests_match_c)'
priority = 80

[[profile.default.overrides]]
filter = 'test(generated_differential) + test(c_testsuite_supported_tests_match_c)'
threads-required = 3
