[profile.slate]
default-filter = '''
  binary_id(=slate::differential)
  + binary_id(=slate::c_testsuite_suite)
  + binary_id(=slate::gcc_torture_suite)
  + binary_id(=slate::gcc_dg_suite)
'''

[profile.parser]
default-filter = 'package(slate-parser)'

[[profile.default.overrides]]
filter = 'test(gcc_torture_supported_tests_match_c)'
threads-required = "num-test-threads"
priority = 100

[[profile.default.overrides]]
filter = 'test(generated_differential)'
priority = 90

[[profile.default.overrides]]
filter = 'test(c_testsuite_supported_tests_match_c)'
priority = 80

[[profile.default.overrides]]
filter = 'test(generated_differential) + test(c_testsuite_supported_tests_match_c)'
threads-required = 3
