[package]
name = "slate-sysroots"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
ar.workspace = true
directories.workspace = true
indicatif.workspace = true
sha2.workspace = true
tar.workspace = true
ureq.workspace = true
xwin.workspace = true
xz2.workspace = true
zip = { workspace = true, features = ["deflate"] }
