#!/usr/bin/env python3
"""Regenerate src/pp/has_checks/clang.rs.

Asks the installed clang which warning groups `__has_warning` knows (the
candidates are `diagtool tree`'s) and which identifiers `__is_identifier`
treats as keywords in each C mode (the candidates are every identifier-shaped
string in libclang-cpp). Each keyword is sorted into the `KeywordModes` of
the modes where clang reserves it; one that fits none is an error.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "pp" / "has_checks" / "clang.rs"
IDENTIFIER = re.compile(rb"[A-Za-z_][A-Za-z0-9_]{1,40}")
STANDARDS = [(year, gnu) for year in ["89", "99", "11", "17", "23", "2y"] for gnu in [False, True]]
MODES = [(year, gnu, ms) for year, gnu in STANDARDS for ms in [False, True]]
CATEGORIES = {
    "Always": lambda year, gnu, ms: True,
    "Microsoft": lambda year, gnu, ms: ms,
    "C99": lambda year, gnu, ms: year != "89",
    "C23": lambda year, gnu, ms: year in ("23", "2y"),
    "Gnu": lambda year, gnu, ms: gnu,
    "GnuOrC99": lambda year, gnu, ms: gnu or year != "89",
    "GnuOrC23": lambda year, gnu, ms: gnu or year in ("23", "2y"),
}


def run(command, stdin=None):
    return subprocess.run(command, capture_output=True, check=False, text=True, input=stdin).stdout


def probe(arguments, lines):
    with tempfile.TemporaryDirectory() as directory:
        source = Path(directory) / "probe.c"
        source.write_text("".join(lines))
        return run(["clang", *arguments, "-undef", "-E", "-P", str(source)]).splitlines()


def warning_groups():
    candidates = set(re.findall(r"-W([A-Za-z0-9=_+#.-]+)", run(["diagtool", "tree"])))
    output = probe(
        [],
        [f'#if __has_warning("-W{name}")\nSLATE_HAS {name}\n#endif\n' for name in sorted(candidates)],
    )
    return {line.split()[1] for line in output if line.startswith("SLATE_HAS ")}


def mode_arguments(year, gnu, ms):
    return [f"-std={'gnu' if gnu else 'c'}{year}"] + (["-fms-extensions"] if ms else [])


def keywords(candidates):
    def reserved(arguments, names):
        output = probe(
            arguments,
            [f"#if !__is_identifier({name})\nSLATE_KEYWORD {name}\n#endif\n" for name in sorted(names)],
        )
        return {line.split()[1] for line in output if line.startswith("SLATE_KEYWORD ")}

    widest = reserved(mode_arguments("2y", True, True), candidates)
    per_mode = {mode: reserved(mode_arguments(*mode), widest) for mode in MODES}
    table = {}
    for name in widest:
        pattern = [name in per_mode[mode] for mode in MODES]
        category = next(
            (
                category
                for category, admits in CATEGORIES.items()
                if pattern == [admits(*mode) for mode in MODES]
            ),
            None,
        )
        if category is None:
            sys.exit(f"{name}: reserved in no known combination of modes: {pattern}")
        table[name] = category
    return table


def main():
    clang_library = next(
        line.split("=>")[1].split()[0]
        for line in run(["ldd", run(["which", "clang"]).strip()]).splitlines()
        if "libclang-cpp" in line
    )
    candidates = {match.group().decode() for match in IDENTIFIER.finditer(Path(clang_library).read_bytes())}
    groups = warning_groups()
    reserved = keywords(candidates)
    clang_version = run(["clang", "--version"]).splitlines()[0]
    warning_rows = "".join(f'    "{name}",\n' for name in sorted(groups))
    keyword_rows = "".join(
        f'    ("{name}", KeywordModes::{category}),\n' for name, category in sorted(reserved.items())
    )
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(
        f"// @generated by tools/generate_clang_pp_tables.py from {clang_version}; do not edit.\n\n"
        "use super::KeywordModes;\n\n"
        f"pub(super) const WARNING_GROUPS: &[&str] = &[\n{warning_rows}];\n\n"
        f"pub(super) const KEYWORDS: &[(&str, KeywordModes)] = &[\n{keyword_rows}];\n"
    )
    print(f"{len(groups)} warning groups, {len(reserved)} keywords", file=sys.stderr)


if __name__ == "__main__":
    main()
