#!/usr/bin/env python3
"""Regenerate src/attribute_support/registered.rs.

Asks each installed compiler's own `__has_attribute` which GNU attribute
spellings it registers, and `__has_c_attribute` which `[[scope::name]]` ones,
over every identifier-shaped string in its binaries.
A name counts as registered if any probed target registers it; the
hand-maintained table in src/attribute_support.rs refines the modeled ones
per target.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "attribute_support" / "registered.rs"
IDENTIFIER = re.compile(rb"[A-Za-z_][A-Za-z0-9_]{2,40}")

CLANG_TRIPLES = [
    "x86_64-linux-gnu",
    "i686-linux-gnu",
    "aarch64-linux-gnu",
    "armv7-linux-gnueabihf",
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
]
GCC_DRIVERS = ["gcc", "aarch64-linux-gnu-gcc"]


def strings(path):
    data = Path(path).read_bytes()
    return {match.group().decode() for match in IDENTIFIER.finditer(data)}


def run(command):
    return subprocess.run(command, capture_output=True, check=False, text=True).stdout


def registered(compiler, candidates, scope=None):
    def query(name):
        if scope is None:
            return f"__has_attribute({name})"
        return f"__has_c_attribute({scope}::{name})"

    with tempfile.TemporaryDirectory() as directory:
        source = Path(directory) / "probe.c"
        source.write_text(
            "".join(
                f"#if {query(name)}\nSLATE_HAS {name}\n#endif\n"
                for name in sorted(candidates)
            )
        )
        output = run([*compiler, "-undef", "-E", "-P", str(source)])
    names = {line.split()[1] for line in output.splitlines() if line.startswith("SLATE_HAS ")}
    return {unwrapped(name) for name in names}


def unwrapped(name):
    if len(name) > 4 and name.startswith("__") and name.endswith("__"):
        return name[2:-2]
    return name


def main():
    gcc_binaries = [run([driver, "-print-prog-name=cc1"]).strip() for driver in GCC_DRIVERS]
    clang_library = next(
        line.split("=>")[1].split()[0]
        for line in run(["ldd", run(["which", "clang"]).strip()]).splitlines()
        if "libclang-cpp" in line
    )
    candidates = set()
    for binary in [*gcc_binaries, clang_library]:
        candidates |= strings(binary)
    print(f"{len(candidates)} candidates", file=sys.stderr)

    clang_compilers = [["clang", f"--target={triple}"] for triple in CLANG_TRIPLES]
    gcc_compilers = [[driver] for driver in GCC_DRIVERS]

    def union(compilers, scope=None):
        names = set()
        for compiler in compilers:
            names |= registered(compiler, candidates, scope)
        return names

    tables = {
        "CLANG": union(clang_compilers),
        "GCC": union(gcc_compilers),
        "CLANG_GNU_SCOPE": union(clang_compilers, "gnu"),
        "CLANG_CLANG_SCOPE": union(clang_compilers, "clang"),
        "CLANG_MSVC_SCOPE": union(clang_compilers, "msvc"),
        "GCC_GNU_SCOPE": union(gcc_compilers, "gnu"),
    }

    clang_version = run(["clang", "--version"]).splitlines()[0]
    gcc_version = run(["gcc", "--version"]).splitlines()[0]

    def table(name, names):
        rows = "".join(f'    "{entry}",\n' for entry in sorted(names))
        return f"pub(super) const {name}: &[&str] = &[\n{rows}];\n"

    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(
        "// @generated by tools/generate_attribute_lists.py from "
        f"{clang_version} and {gcc_version}; do not edit.\n\n"
        + "\n".join(table(name, names) for name, names in tables.items())
    )
    for name, names in tables.items():
        print(f"{name} {len(names)}", file=sys.stderr)


if __name__ == "__main__":
    main()
