#!/usr/bin/env python3
"""Regenerate the table of contents in every wiki/concepts page.

The TOC sits between `<!-- toc -->` and `<!-- /toc -->` right after the page
title and lists `##` and `###` headings with GitHub anchors, generated by
pandoc. Pages with fewer than three such headings get no TOC.

    python3 tools/wiki_toc.py          # rewrite pages in place
    python3 tools/wiki_toc.py --check  # exit 1 if any page is stale
"""

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONCEPTS = ROOT / "wiki" / "concepts"
BEGIN = "<!-- toc -->"
END = "<!-- /toc -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", re.S)
MIN_ENTRIES = 3


def toc(text: str, template: Path) -> str:
    result = subprocess.run(
        [
            "pandoc",
            "--from=gfm",
            "--to=gfm",
            "--shift-heading-level-by=-1",
            "--toc",
            "--toc-depth=2",
            "--standalone",
            f"--template={template}",
        ],
        input=text,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def render(text: str, template: Path) -> str:
    body = BLOCK.sub("", text)
    listing = toc(body, template)
    if sum(line.lstrip().startswith("- [") for line in listing.splitlines()) < MIN_ENTRIES:
        return body
    title, sep, rest = body.partition("\n")
    if not title.startswith("# "):
        return body
    return f"{title}\n\n{BEGIN}\n{listing}\n{END}\n\n{rest.lstrip(chr(10))}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report stale pages without writing")
    args = parser.parse_args()

    stale = []
    with tempfile.TemporaryDirectory() as tmp:
        template = Path(tmp) / "toc.tpl"
        template.write_text("$toc$\n")
        for page in sorted(CONCEPTS.rglob("*.md")):
            text = page.read_text()
            updated = render(text, template)
            if updated == text:
                continue
            stale.append(page.relative_to(ROOT))
            if not args.check:
                page.write_text(updated)

    for page in stale:
        print(f"{'stale' if args.check else 'updated'}: {page}")
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
